// MongoDB Compass Commands to Insert Comprehensive Government Schemes
// Copy and paste these commands in MongoDB Compass Query/Aggregation tab

// Use the Govt_schemes database
use('Govt_schemes');

// Insert Major Central Government Schemes
db.government_schemes.insertMany([
  {
    "title": "Kisan Credit Card (KCC) Scheme",
    "description": "The Kisan Credit Card scheme provides farmers with timely access to credit for their cultivation and other needs. It offers flexible repayment terms and covers crop loans, post-harvest expenses, and investment credit requirements.",
    "short_description": "Credit card facility for farmers with flexible repayment terms",
    "sector": "agriculture",
    "ministry": "Ministry of Agriculture and Farmers Welfare",
    "department": "Department of Agriculture, Cooperation and Farmers Welfare",
    "government_level": "central",
    "eligibility_criteria": "All farmers including tenant farmers, oral lessees, and sharecroppers",
    "benefits": "Credit limit up to ₹3 lakh without collateral, 4% interest rate with prompt repayment incentive",
    "application_process": "Apply through any bank branch or cooperative society",
    "launch_date": "1998-08-01",
    "helpline_number": "1800-180-1551",
    "website": "https://pmkisan.gov.in/",
    "source_url": "https://pmkisan.gov.in/",
    "keywords": ["kisan credit card", "farmer loan", "agriculture credit", "kcc"],
    "search_tags": ["agriculture", "central", "credit", "farmers"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
    "description": "MGNREGA guarantees 100 days of wage employment per year to every rural household whose adult members volunteer to do unskilled manual work.",
    "short_description": "100 days guaranteed employment for rural households",
    "sector": "employment",
    "ministry": "Ministry of Rural Development",
    "department": "Department of Rural Development",
    "government_level": "central",
    "eligibility_criteria": "Adult members of rural households willing to do unskilled manual work",
    "benefits": "100 days of guaranteed wage employment per household per year",
    "application_process": "Apply at Gram Panchayat office with job card",
    "launch_date": "2005-08-25",
    "helpline_number": "1800-345-22-44",
    "website": "https://nrega.nic.in/",
    "source_url": "https://nrega.nic.in/",
    "keywords": ["mgnrega", "rural employment", "job guarantee", "wage employment"],
    "search_tags": ["employment", "central", "rural", "guarantee"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "National Scholarship Portal (NSP)",
    "description": "NSP is a one-stop solution for various scholarship schemes. It provides a common platform for application, processing, and disbursal of scholarships.",
    "short_description": "Unified platform for various scholarship schemes",
    "sector": "education",
    "ministry": "Ministry of Education",
    "department": "Department of Higher Education",
    "government_level": "central",
    "eligibility_criteria": "Students from various categories based on merit and need",
    "benefits": "Scholarships ranging from ₹1,000 to ₹20,000 per year",
    "application_process": "Apply online through National Scholarship Portal",
    "launch_date": "2011-01-01",
    "helpline_number": "0120-6619540",
    "website": "https://scholarships.gov.in/",
    "source_url": "https://scholarships.gov.in/",
    "keywords": ["scholarship", "nsp", "student financial aid"],
    "search_tags": ["education", "central", "scholarship", "students"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Pradhan Mantri Ujjwala Yojana (PMUY)",
    "description": "PMUY aims to provide LPG connections to women from Below Poverty Line (BPL) households. The scheme ensures universal coverage of cooking gas in the country.",
    "short_description": "Free LPG connections for BPL women",
    "sector": "social_welfare",
    "ministry": "Ministry of Petroleum and Natural Gas",
    "department": "Department of Petroleum and Natural Gas",
    "government_level": "central",
    "eligibility_criteria": "Women from BPL households, priority to SC/ST, PMAY, AAY beneficiaries",
    "benefits": "Free LPG connection with deposit-free cylinder and pressure regulator",
    "application_process": "Apply through LPG distributors with required documents",
    "launch_date": "2016-05-01",
    "helpline_number": "1800-266-6696",
    "website": "https://pmuy.gov.in/",
    "source_url": "https://pmuy.gov.in/",
    "keywords": ["ujjwala", "lpg connection", "cooking gas", "women empowerment"],
    "search_tags": ["social welfare", "central", "lpg", "women"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Pradhan Mantri Awas Yojana (PMAY)",
    "description": "PMAY aims to provide affordable housing to the urban and rural poor. It has two components: PMAY-Urban and PMAY-Gramin for comprehensive housing coverage.",
    "short_description": "Affordable housing scheme for urban and rural poor",
    "sector": "housing",
    "ministry": "Ministry of Housing and Urban Affairs",
    "department": "Department of Housing and Urban Affairs",
    "government_level": "central",
    "eligibility_criteria": "Families without pucca house, income criteria varies by category",
    "benefits": "Interest subsidy up to ₹2.67 lakh, direct assistance up to ₹1.2 lakh",
    "application_process": "Apply online through PMAY portal or Common Service Centers",
    "launch_date": "2015-06-25",
    "helpline_number": "1800-11-6446",
    "website": "https://pmaymis.gov.in/",
    "source_url": "https://pmaymis.gov.in/",
    "keywords": ["pmay", "housing", "affordable housing", "home loan subsidy"],
    "search_tags": ["housing", "central", "affordable", "subsidy"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    "description": "PM-KISAN provides income support of ₹6,000 per year to all landholding farmer families across the country. The amount is transferred directly to bank accounts in three equal installments.",
    "short_description": "₹6,000 annual income support for farmers",
    "sector": "agriculture",
    "ministry": "Ministry of Agriculture and Farmers Welfare",
    "department": "Department of Agriculture, Cooperation and Farmers Welfare",
    "government_level": "central",
    "eligibility_criteria": "All landholding farmer families irrespective of size of landholding",
    "benefits": "₹6,000 per year in three installments of ₹2,000 each",
    "application_process": "Apply online through PM-KISAN portal or Common Service Centers",
    "launch_date": "2019-02-24",
    "helpline_number": "155261",
    "website": "https://pmkisan.gov.in/",
    "source_url": "https://pmkisan.gov.in/",
    "keywords": ["pm kisan", "farmer income support", "direct benefit transfer"],
    "search_tags": ["agriculture", "central", "income support", "farmers"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
    "description": "AB-PMJAY is the world's largest health insurance scheme providing health coverage of ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
    "short_description": "₹5 lakh health insurance coverage per family",
    "sector": "health",
    "ministry": "Ministry of Health and Family Welfare",
    "department": "National Health Authority",
    "government_level": "central",
    "eligibility_criteria": "Families identified through SECC-2011 database, approximately 10.74 crore vulnerable families",
    "benefits": "Health insurance coverage up to ₹5 lakh per family per year",
    "application_process": "Eligible families get cards automatically, treatment at empaneled hospitals",
    "launch_date": "2018-09-23",
    "helpline_number": "14555",
    "website": "https://pmjay.gov.in/",
    "source_url": "https://pmjay.gov.in/",
    "keywords": ["ayushman bharat", "health insurance", "pmjay", "medical coverage"],
    "search_tags": ["health", "central", "insurance", "medical"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
    "description": "PMKVY is the flagship scheme of the Ministry of Skill Development and Entrepreneurship. It aims to enable a large number of Indian youth to take up industry-relevant skill training.",
    "short_description": "Skill development and training program for youth",
    "sector": "employment",
    "ministry": "Ministry of Skill Development and Entrepreneurship",
    "department": "Department of Skill Development and Entrepreneurship",
    "government_level": "central",
    "eligibility_criteria": "Indian citizens aged 15-45 years, priority to youth from disadvantaged sections",
    "benefits": "Free skill training, certification, and monetary rewards up to ₹8,000",
    "application_process": "Apply through PMKVY centers or online portal",
    "launch_date": "2015-07-15",
    "helpline_number": "8800055555",
    "website": "https://pmkvyofficial.org/",
    "source_url": "https://pmkvyofficial.org/",
    "keywords": ["skill development", "pmkvy", "vocational training", "youth employment"],
    "search_tags": ["employment", "central", "skill", "training"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Digital India Programme",
    "description": "Digital India is a campaign launched to ensure that Government services are made available to citizens electronically by improved online infrastructure and by increasing Internet connectivity.",
    "short_description": "Digital transformation and e-governance initiative",
    "sector": "urban_development",
    "ministry": "Ministry of Electronics and Information Technology",
    "department": "Department of Electronics and Information Technology",
    "government_level": "central",
    "eligibility_criteria": "All citizens and government departments",
    "benefits": "Digital services, e-governance, digital literacy, broadband connectivity",
    "application_process": "Access digital services through various government portals",
    "launch_date": "2015-07-01",
    "helpline_number": "1800-233-7677",
    "website": "https://digitalindia.gov.in/",
    "source_url": "https://digitalindia.gov.in/",
    "keywords": ["digital india", "e-governance", "digital services", "technology"],
    "search_tags": ["urban development", "central", "digital", "technology"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  },
  {
    "title": "Swachh Bharat Mission",
    "description": "Swachh Bharat Mission aims to achieve universal sanitation coverage and to put focus on sanitation and solid waste management. It has two sub-missions: Swachh Bharat Mission (Gramin) and Swachh Bharat Mission (Urban).",
    "short_description": "Clean India mission for sanitation and waste management",
    "sector": "urban_development",
    "ministry": "Ministry of Jal Shakti",
    "department": "Department of Drinking Water and Sanitation",
    "government_level": "central",
    "eligibility_criteria": "All households, communities, and institutions across India",
    "benefits": "Toilet construction incentives, waste management systems, behavioral change",
    "application_process": "Apply through local authorities or online portals",
    "launch_date": "2014-10-02",
    "helpline_number": "1800-11-0001",
    "website": "https://swachhbharatmission.gov.in/",
    "source_url": "https://swachhbharatmission.gov.in/",
    "keywords": ["swachh bharat", "sanitation", "toilet", "cleanliness", "waste management"],
    "search_tags": ["urban development", "central", "sanitation", "cleanliness"],
    "is_active": true,
    "created_at": new Date(),
    "updated_at": new Date()
  }
]);

// Check total count after insertion
db.government_schemes.countDocuments({});

// Check schemes by sector
db.government_schemes.aggregate([
  { $group: { _id: "$sector", count: { $sum: 1 } } },
  { $sort: { count: -1 } }
]);

// Verify the new schemes were added
db.government_schemes.find(
  { "government_level": "central" },
  { "title": 1, "sector": 1, "_id": 0 }
).sort({ "title": 1 });
