import os
import pymongo
from datetime import datetime
import json

# MongoDB connection
MONGODB_URI = 'mongodb://localhost:27017/'
MONGODB_DATABASE = 'Govt_schemes'  # Match case with existing database

def connect_mongodb():
    """Connect to MongoDB and return database object"""
    try:
        client = pymongo.MongoClient(MONGODB_URI)
        db = client[MONGODB_DATABASE]
        # Test connection
        client.admin.command('ping')
        print("[OK] MongoDB connection successful!")
        return db
    except Exception as e:
        print(f"[ERROR] MongoDB connection failed: {e}")
        return None

def create_comprehensive_sample_data():
    """Create comprehensive sample data for demo"""
    
    # Comprehensive government schemes data
    schemes_data = [
        # Agriculture Schemes (5 schemes)
        {
            "title": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
            "description": "PM-KISAN is a Central Sector Scheme with 100% funding from Government of India. Under the scheme, income support of Rs.6000/- per year is provided to all farmer families across the country in three equal installments of Rs.2000/- each every four months.",
            "short_description": "Income support of Rs.6000/- per year to all farmer families",
            "sector": "agriculture",
            "ministry": "Ministry of Agriculture and Farmers Welfare",
            "department": "Department of Agriculture, Cooperation and Farmers Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All landholding farmer families with cultivable land in their names",
            "benefits": "Rs.6000/- per year in three equal installments of Rs.2000/- each",
            "application_process": "Registration through Common Service Centres (CSC) or online portal",
            "application_link": "https://pmkisan.gov.in/",
            "launch_date": "2019-02-01",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@pmkisan.gov.in",
            "website": "https://pmkisan.gov.in/",
            "source_url": "https://pmkisan.gov.in/",
            "keywords": ["farmer", "agriculture", "income support", "pm-kisan", "kisan samman"],
            "search_tags": ["agriculture", "central", "farmer welfare", "income support"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
            "description": "PMFBY is a crop insurance scheme that provides comprehensive insurance coverage against crop failure, helping to stabilize the income of farmers and encourage them to adopt innovative and modern agricultural practices.",
            "short_description": "Crop insurance scheme for farmers",
            "sector": "agriculture",
            "ministry": "Ministry of Agriculture and Farmers Welfare",
            "department": "Department of Agriculture, Cooperation and Farmers Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All farmers growing notified crops in notified areas",
            "benefits": "Premium subsidy up to 90% for small and marginal farmers",
            "application_process": "Registration through Common Service Centres (CSC) or online portal",
            "application_link": "https://pmfby.gov.in/",
            "launch_date": "2016-02-18",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@pmfby.gov.in",
            "website": "https://pmfby.gov.in/",
            "source_url": "https://pmfby.gov.in/",
            "keywords": ["crop insurance", "agriculture", "farmers", "pmfby", "fasal bima"],
            "search_tags": ["agriculture", "central", "crop insurance", "farmers"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Soil Health Card Scheme",
            "description": "The Soil Health Card Scheme aims to provide farmers with soil health cards containing crop-wise recommendations of nutrients and fertilizers required for their farms.",
            "short_description": "Soil health assessment and recommendations for farmers",
            "sector": "agriculture",
            "ministry": "Ministry of Agriculture and Farmers Welfare",
            "department": "Department of Agriculture, Cooperation and Farmers Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All farmers with agricultural land",
            "benefits": "Free soil testing and recommendations",
            "application_process": "Application through Krishi Vigyan Kendras or online",
            "application_link": "https://soilhealth.dac.gov.in/",
            "launch_date": "2015-02-19",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@soilhealth.gov.in",
            "website": "https://soilhealth.dac.gov.in/",
            "source_url": "https://soilhealth.dac.gov.in/",
            "keywords": ["soil health", "agriculture", "farmers", "soil testing", "fertilizer"],
            "search_tags": ["agriculture", "central", "soil health", "farmers"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Krishi Sinchai Yojana (PMKSY)",
            "description": "PMKSY aims to enhance physical access of water on the farm and expand cultivable area under assured irrigation, improve on-farm water use efficiency, and introduce sustainable water conservation practices.",
            "short_description": "Irrigation and water conservation scheme for farmers",
            "sector": "agriculture",
            "ministry": "Ministry of Agriculture and Farmers Welfare",
            "department": "Department of Agriculture, Cooperation and Farmers Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Farmers with agricultural land",
            "benefits": "Subsidy for irrigation infrastructure and water conservation",
            "application_process": "Application through state agriculture departments",
            "application_link": None,
            "launch_date": "2015-07-01",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@pmksy.gov.in",
            "website": "https://pmksy.gov.in/",
            "source_url": "https://pmksy.gov.in/",
            "keywords": ["irrigation", "agriculture", "water conservation", "pmksy", "farmers"],
            "search_tags": ["agriculture", "central", "irrigation", "water conservation"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "National Mission for Sustainable Agriculture (NMSA)",
            "description": "NMSA aims to promote sustainable agriculture through climate change adaptation measures, enhanced water use efficiency, soil health management, and integrated farming systems.",
            "short_description": "Sustainable agriculture and climate change adaptation",
            "sector": "agriculture",
            "ministry": "Ministry of Agriculture and Farmers Welfare",
            "department": "Department of Agriculture, Cooperation and Farmers Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Farmers and farmer groups",
            "benefits": "Financial assistance for sustainable agriculture practices",
            "application_process": "Application through state agriculture departments",
            "application_link": None,
            "launch_date": "2010-04-01",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@nmsa.gov.in",
            "website": "https://nmsa.dac.gov.in/",
            "source_url": "https://nmsa.dac.gov.in/",
            "keywords": ["sustainable agriculture", "climate change", "agriculture", "nmsa"],
            "search_tags": ["agriculture", "central", "sustainable", "climate change"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },

        # Health Schemes (5 schemes)
        {
            "title": "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
            "description": "AB-PMJAY is the world's largest health insurance scheme providing health coverage of Rs.5 lakh per family per year for secondary and tertiary care hospitalization.",
            "short_description": "Health insurance scheme providing Rs.5 lakh coverage per family",
            "sector": "health",
            "ministry": "Ministry of Health and Family Welfare",
            "department": "Department of Health and Family Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Families identified as deprived rural families and occupational categories of urban workers' families",
            "benefits": "Health coverage of Rs.5 lakh per family per year",
            "application_process": "Registration through Common Service Centres or online",
            "application_link": "https://pmjay.gov.in/",
            "launch_date": "2018-09-23",
            "last_date": None,
            "helpline_number": "1800-111-565",
            "email": "support@pmjay.gov.in",
            "website": "https://pmjay.gov.in/",
            "source_url": "https://pmjay.gov.in/",
            "keywords": ["health", "medical", "hospitalization", "ayushman bharat", "insurance"],
            "search_tags": ["health", "central", "medical insurance", "hospitalization"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
            "description": "PMMVY is a maternity benefit program that provides financial assistance to pregnant and lactating mothers for their first living child.",
            "short_description": "Maternity benefit program for pregnant women",
            "sector": "health",
            "ministry": "Ministry of Women and Child Development",
            "department": "Department of Women and Child Development",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Pregnant and lactating mothers above 19 years of age",
            "benefits": "Rs.5000/- in three installments",
            "application_process": "Registration at Anganwadi Centres or online",
            "application_link": "https://wcd.nic.in/",
            "launch_date": "2017-01-01",
            "last_date": None,
            "helpline_number": "1800-180-1104",
            "email": "support@wcd.nic.in",
            "website": "https://wcd.nic.in/",
            "source_url": "https://wcd.nic.in/",
            "keywords": ["maternity", "health", "women", "pregnancy", "pmvvy"],
            "search_tags": ["health", "central", "maternity", "women welfare"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "National Health Mission (NHM)",
            "description": "NHM aims to provide universal access to equitable, affordable, and quality health care services that are accountable and responsive to people's needs.",
            "short_description": "Universal health care access and quality improvement",
            "sector": "health",
            "ministry": "Ministry of Health and Family Welfare",
            "department": "Department of Health and Family Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All citizens",
            "benefits": "Improved health infrastructure and services",
            "application_process": "Services available at government health facilities",
            "application_link": None,
            "launch_date": "2005-04-01",
            "last_date": None,
            "helpline_number": "1800-180-1104",
            "email": "support@nhm.gov.in",
            "website": "https://nhm.gov.in/",
            "source_url": "https://nhm.gov.in/",
            "keywords": ["health", "universal", "healthcare", "nhm", "medical"],
            "search_tags": ["health", "central", "universal healthcare", "medical"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)",
            "description": "PMSSY aims to correct regional imbalances in the availability of affordable/reliable tertiary healthcare services and also to augment facilities for quality medical education.",
            "short_description": "Tertiary healthcare and medical education infrastructure",
            "sector": "health",
            "ministry": "Ministry of Health and Family Welfare",
            "department": "Department of Health and Family Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All citizens",
            "benefits": "Access to tertiary healthcare services",
            "application_process": "Services available at PMSSY hospitals",
            "application_link": None,
            "launch_date": "2003-01-01",
            "last_date": None,
            "helpline_number": "1800-180-1104",
            "email": "support@pmssy.gov.in",
            "website": "https://pmssy.gov.in/",
            "source_url": "https://pmssy.gov.in/",
            "keywords": ["health", "tertiary", "healthcare", "pmssy", "medical"],
            "search_tags": ["health", "central", "tertiary healthcare", "medical"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Janani Suraksha Yojana (JSY)",
            "description": "JSY is a safe motherhood intervention under the National Health Mission to reduce maternal and neonatal mortality by promoting institutional delivery among poor pregnant women.",
            "short_description": "Safe motherhood and institutional delivery program",
            "sector": "health",
            "ministry": "Ministry of Health and Family Welfare",
            "department": "Department of Health and Family Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Pregnant women from BPL families",
            "benefits": "Cash assistance for institutional delivery",
            "application_process": "Registration at government health facilities",
            "application_link": None,
            "launch_date": "2005-04-01",
            "last_date": None,
            "helpline_number": "1800-180-1104",
            "email": "support@jsy.gov.in",
            "website": "https://nhm.gov.in/",
            "source_url": "https://nhm.gov.in/",
            "keywords": ["maternity", "health", "women", "delivery", "jsy"],
            "search_tags": ["health", "central", "maternity", "women welfare"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },

        # Employment Schemes (5 schemes)
        {
            "title": "Pradhan Mantri Mudra Yojana (PMMY)",
            "description": "PMMY is a scheme launched by the Hon'ble Prime Minister on April 8, 2015 for providing loans up to 10 lakh to the non-corporate, non-farm small/micro enterprises.",
            "short_description": "Micro loans for small businesses and entrepreneurs",
            "sector": "employment",
            "ministry": "Ministry of Finance",
            "department": "Department of Financial Services",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Non-corporate, non-farm small/micro enterprises",
            "benefits": "Loans up to Rs.10 lakh",
            "application_process": "Application through banks and financial institutions",
            "application_link": "https://mudra.org.in/",
            "launch_date": "2015-04-08",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@mudra.org.in",
            "website": "https://mudra.org.in/",
            "source_url": "https://mudra.org.in/",
            "keywords": ["loan", "mudra", "small business", "micro enterprise", "employment"],
            "search_tags": ["employment", "central", "loan", "small business"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
            "description": "PMKVY is a skill development initiative that aims to train over 10 million youth in various skills to make them employable.",
            "short_description": "Skill development program for youth",
            "sector": "employment",
            "ministry": "Ministry of Skill Development and Entrepreneurship",
            "department": "Department of Skill Development and Entrepreneurship",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Indian citizens aged 15-45 years",
            "benefits": "Free training and certification with placement assistance",
            "application_process": "Registration through training centers or online portal",
            "application_link": "https://pmkvy.gov.in/",
            "launch_date": "2015-07-15",
            "last_date": None,
            "helpline_number": "1800-123-9626",
            "email": "support@pmkvy.gov.in",
            "website": "https://pmkvy.gov.in/",
            "source_url": "https://pmkvy.gov.in/",
            "keywords": ["skill development", "employment", "training", "pmkvy", "youth"],
            "search_tags": ["employment", "central", "skill development", "youth"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
            "description": "MGNREGA provides at least 100 days of guaranteed wage employment in a financial year to every household whose adult members volunteer to do unskilled manual work.",
            "short_description": "Guaranteed employment for rural households",
            "sector": "employment",
            "ministry": "Ministry of Rural Development",
            "department": "Department of Rural Development",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Adult members of rural households",
            "benefits": "At least 100 days of guaranteed wage employment",
            "application_process": "Registration at Gram Panchayat",
            "application_link": "https://nrega.nic.in/",
            "launch_date": "2006-02-02",
            "last_date": None,
            "helpline_number": "1800-345-3610",
            "email": "support@nrega.nic.in",
            "website": "https://nrega.nic.in/",
            "source_url": "https://nrega.nic.in/",
            "keywords": ["employment", "rural", "mgnrega", "wage", "manual work"],
            "search_tags": ["employment", "central", "rural employment", "wage"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Rojgar Protsahan Yojana (PMRPY)",
            "description": "PMRPY is a scheme to incentivize employers for new employment generation by the Government of India paying the full employer's contribution towards EPF and EPS for new employees.",
            "short_description": "Employment generation incentive for employers",
            "sector": "employment",
            "ministry": "Ministry of Labour and Employment",
            "department": "Department of Labour and Employment",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Employers hiring new employees",
            "benefits": "Government pays employer's EPF contribution",
            "application_process": "Registration through EPFO portal",
            "application_link": "https://epfindia.gov.in/",
            "launch_date": "2016-08-09",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@epfindia.gov.in",
            "website": "https://epfindia.gov.in/",
            "source_url": "https://epfindia.gov.in/",
            "keywords": ["employment", "epf", "employer", "pmrpy", "job creation"],
            "search_tags": ["employment", "central", "epf", "employer"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Startup India Initiative",
            "description": "Startup India is a flagship initiative of the Government of India, intended to build a strong ecosystem for nurturing innovation and startups in the country.",
            "short_description": "Support ecosystem for startups and innovation",
            "sector": "employment",
            "ministry": "Ministry of Commerce and Industry",
            "department": "Department for Promotion of Industry and Internal Trade",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Startups registered under Startup India",
            "benefits": "Tax benefits, funding support, and mentorship",
            "application_process": "Registration through Startup India portal",
            "application_link": "https://startupindia.gov.in/",
            "launch_date": "2016-01-16",
            "last_date": None,
            "helpline_number": "1800-210-5510",
            "email": "support@startupindia.gov.in",
            "website": "https://startupindia.gov.in/",
            "source_url": "https://startupindia.gov.in/",
            "keywords": ["startup", "employment", "innovation", "entrepreneurship", "funding"],
            "search_tags": ["employment", "central", "startup", "innovation"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },

        # Education Schemes (5 schemes)
        {
            "title": "Pradhan Mantri Poshan Shakti Nirman (PM POSHAN)",
            "description": "PM POSHAN is a centrally sponsored scheme that provides hot cooked meals to children studying in classes I to VIII in government and government-aided schools.",
            "short_description": "Mid-day meal program for school children",
            "sector": "education",
            "ministry": "Ministry of Education",
            "department": "Department of School Education and Literacy",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Children studying in classes I to VIII in government schools",
            "benefits": "Hot cooked meals with nutritional value",
            "application_process": "Automatic enrollment in government schools",
            "application_link": None,
            "launch_date": "2021-09-29",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@education.gov.in",
            "website": "https://education.gov.in/",
            "source_url": "https://education.gov.in/",
            "keywords": ["education", "mid-day meal", "school", "nutrition", "children"],
            "search_tags": ["education", "central", "mid-day meal", "school nutrition"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Samagra Shiksha Abhiyan",
            "description": "Samagra Shiksha is an integrated scheme for school education extending from pre-school to class XII to ensure inclusive and equitable quality education.",
            "short_description": "Integrated scheme for school education",
            "sector": "education",
            "ministry": "Ministry of Education",
            "department": "Department of School Education and Literacy",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All school-going children",
            "benefits": "Quality education infrastructure and teacher support",
            "application_process": "Services available in government schools",
            "application_link": None,
            "launch_date": "2018-04-01",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@education.gov.in",
            "website": "https://education.gov.in/",
            "source_url": "https://education.gov.in/",
            "keywords": ["education", "school", "samagra", "quality education", "children"],
            "search_tags": ["education", "central", "school education", "quality"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Schools for Rising India (PM-SHRI)",
            "description": "PM-SHRI is a scheme to upgrade and develop more than 14,500 schools across the country to showcase the implementation of the National Education Policy 2020.",
            "short_description": "Model schools showcasing NEP 2020 implementation",
            "sector": "education",
            "ministry": "Ministry of Education",
            "department": "Department of School Education and Literacy",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Schools selected by state governments",
            "benefits": "Upgraded infrastructure and modern teaching methods",
            "application_process": "Selection through state education departments",
            "application_link": None,
            "launch_date": "2022-09-05",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@education.gov.in",
            "website": "https://education.gov.in/",
            "source_url": "https://education.gov.in/",
            "keywords": ["education", "school", "pm-shri", "nep 2020", "model schools"],
            "search_tags": ["education", "central", "model schools", "nep 2020"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Digital India e-Learning",
            "description": "Digital India e-Learning initiative provides digital learning resources and platforms to enhance educational access and quality across the country.",
            "short_description": "Digital learning resources and platforms",
            "sector": "education",
            "ministry": "Ministry of Education",
            "department": "Department of School Education and Literacy",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Students and teachers",
            "benefits": "Access to digital learning resources",
            "application_process": "Registration through digital platforms",
            "application_link": "https://diksha.gov.in/",
            "launch_date": "2015-07-01",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@diksha.gov.in",
            "website": "https://diksha.gov.in/",
            "source_url": "https://diksha.gov.in/",
            "keywords": ["education", "digital", "e-learning", "online", "students"],
            "search_tags": ["education", "central", "digital learning", "online"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Innovative Learning Programme (PMILP)",
            "description": "PMILP aims to identify and nurture innovative and creative minds among school students and provide them with opportunities to work with leading scientists and institutions.",
            "short_description": "Innovation and creativity program for students",
            "sector": "education",
            "ministry": "Ministry of Education",
            "department": "Department of School Education and Literacy",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "School students with innovative ideas",
            "benefits": "Mentorship and support for innovative projects",
            "application_process": "Application through schools",
            "application_link": None,
            "launch_date": "2020-01-01",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@education.gov.in",
            "website": "https://education.gov.in/",
            "source_url": "https://education.gov.in/",
            "keywords": ["education", "innovation", "students", "creativity", "science"],
            "search_tags": ["education", "central", "innovation", "students"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },

        # Social Welfare Schemes (5 schemes)
        {
            "title": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
            "description": "PMJDY is a National Mission for Financial Inclusion to ensure access to financial services, namely, Banking Savings & Deposit Accounts, Remittance, Credit, Insurance, Pension in an affordable manner.",
            "short_description": "Financial inclusion through bank accounts",
            "sector": "social_welfare",
            "ministry": "Ministry of Finance",
            "department": "Department of Financial Services",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All citizens without bank accounts",
            "benefits": "Zero balance bank account with debit card",
            "application_process": "Application through banks or Common Service Centres",
            "application_link": "https://pmjdy.gov.in/",
            "launch_date": "2014-08-28",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@pmjdy.gov.in",
            "website": "https://pmjdy.gov.in/",
            "source_url": "https://pmjdy.gov.in/",
            "keywords": ["banking", "financial inclusion", "jan dhan", "savings account", "social welfare"],
            "search_tags": ["social welfare", "central", "banking", "financial inclusion"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Ujjwala Yojana (PMUY)",
            "description": "PMUY is a scheme to provide LPG connections to women from below poverty line (BPL) households.",
            "short_description": "LPG connection scheme for BPL women",
            "sector": "social_welfare",
            "ministry": "Ministry of Petroleum and Natural Gas",
            "department": "Department of Petroleum and Natural Gas",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Women from BPL households",
            "benefits": "Free LPG connection with first refill",
            "application_process": "Application through LPG distributors",
            "application_link": "https://petroleum.nic.in/",
            "launch_date": "2016-05-01",
            "last_date": None,
            "helpline_number": "1800-266-6696",
            "email": "support@petroleum.nic.in",
            "website": "https://petroleum.nic.in/",
            "source_url": "https://petroleum.nic.in/",
            "keywords": ["lpg", "social welfare", "women", "bpl", "ujjwala"],
            "search_tags": ["social welfare", "central", "lpg", "women welfare"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Garib Kalyan Anna Yojana (PMGKAY)",
            "description": "PMGKAY provides free food grains to all beneficiaries covered under the National Food Security Act (NFSA) to reduce the hardship faced by the poor due to economic disruption.",
            "short_description": "Free food grains for NFSA beneficiaries",
            "sector": "social_welfare",
            "ministry": "Ministry of Consumer Affairs, Food and Public Distribution",
            "department": "Department of Food and Public Distribution",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "NFSA beneficiaries",
            "benefits": "Free food grains (rice/wheat)",
            "application_process": "Automatic distribution through PDS",
            "application_link": None,
            "launch_date": "2020-04-01",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@dfpd.gov.in",
            "website": "https://dfpd.gov.in/",
            "source_url": "https://dfpd.gov.in/",
            "keywords": ["food", "social welfare", "pds", "nfsa", "free grains"],
            "search_tags": ["social welfare", "central", "food security", "pds"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
            "description": "PMAY-G aims to provide a pucca house with basic amenities to all houseless households and those living in kutcha and dilapidated houses in rural areas.",
            "short_description": "Housing scheme for rural areas",
            "sector": "social_welfare",
            "ministry": "Ministry of Rural Development",
            "department": "Department of Rural Development",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Houseless households and those in kutcha houses",
            "benefits": "Financial assistance for pucca house construction",
            "application_process": "Application through Gram Panchayat",
            "application_link": "https://pmayg.nic.in/",
            "launch_date": "2016-04-01",
            "last_date": None,
            "helpline_number": "1800-345-3610",
            "email": "support@pmayg.nic.in",
            "website": "https://pmayg.nic.in/",
            "source_url": "https://pmayg.nic.in/",
            "keywords": ["housing", "social welfare", "rural", "pmay-g", "house construction"],
            "search_tags": ["social welfare", "central", "housing", "rural"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Kisan Maan Dhan Yojana (PMKMDY)",
            "description": "PMKMDY is a voluntary and contributory pension scheme for small and marginal farmers to provide them with a minimum assured pension of Rs.3000/- per month.",
            "short_description": "Pension scheme for small and marginal farmers",
            "sector": "social_welfare",
            "ministry": "Ministry of Agriculture and Farmers Welfare",
            "department": "Department of Agriculture, Cooperation and Farmers Welfare",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Small and marginal farmers aged 18-40 years",
            "benefits": "Minimum assured pension of Rs.3000/- per month",
            "application_process": "Registration through Common Service Centres",
            "application_link": "https://pmkmy.gov.in/",
            "launch_date": "2019-09-12",
            "last_date": None,
            "helpline_number": "1800-180-1551",
            "email": "support@pmkmy.gov.in",
            "website": "https://pmkmy.gov.in/",
            "source_url": "https://pmkmy.gov.in/",
            "keywords": ["pension", "social welfare", "farmers", "pmkmdy", "retirement"],
            "search_tags": ["social welfare", "central", "pension", "farmers"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },

        # Urban Development Schemes (5 schemes)
        {
            "title": "Pradhan Mantri Awas Yojana - Urban (PMAY-U)",
            "description": "PMAY-U aims to provide housing for all in urban areas by the year 2022 through various verticals including in-situ slum redevelopment, credit linked subsidy, affordable housing in partnership, and beneficiary-led individual house construction.",
            "short_description": "Housing scheme for urban areas",
            "sector": "urban_development",
            "ministry": "Ministry of Housing and Urban Affairs",
            "department": "Department of Housing and Urban Affairs",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Economically weaker sections and low-income groups",
            "benefits": "Financial assistance for house construction or purchase",
            "application_process": "Application through urban local bodies",
            "application_link": "https://pmaymis.gov.in/",
            "launch_date": "2015-06-25",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@pmaymis.gov.in",
            "website": "https://pmaymis.gov.in/",
            "source_url": "https://pmaymis.gov.in/",
            "keywords": ["housing", "urban development", "pmay-u", "affordable housing"],
            "search_tags": ["urban development", "central", "housing", "affordable"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Smart Cities Mission",
            "description": "Smart Cities Mission is an urban renewal and retrofitting program to develop 100 cities across the country making them citizen friendly and sustainable.",
            "short_description": "Urban development program for smart cities",
            "sector": "urban_development",
            "ministry": "Ministry of Housing and Urban Affairs",
            "department": "Department of Housing and Urban Affairs",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Cities selected through competition",
            "benefits": "Infrastructure development and smart solutions",
            "application_process": "City selection through competition",
            "application_link": "https://smartcities.gov.in/",
            "launch_date": "2015-06-25",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@smartcities.gov.in",
            "website": "https://smartcities.gov.in/",
            "source_url": "https://smartcities.gov.in/",
            "keywords": ["smart cities", "urban development", "infrastructure", "sustainable"],
            "search_tags": ["urban development", "central", "smart cities", "infrastructure"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Atal Mission for Rejuvenation and Urban Transformation (AMRUT)",
            "description": "AMRUT focuses on the creation of infrastructure that could have a direct impact on the lives of people in urban areas.",
            "short_description": "Urban infrastructure development mission",
            "sector": "urban_development",
            "ministry": "Ministry of Housing and Urban Affairs",
            "department": "Department of Housing and Urban Affairs",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Cities with population above 1 lakh",
            "benefits": "Improved urban infrastructure and services",
            "application_process": "Implementation through state governments",
            "application_link": None,
            "launch_date": "2015-06-25",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@amrut.gov.in",
            "website": "https://amrut.gov.in/",
            "source_url": "https://amrut.gov.in/",
            "keywords": ["urban development", "infrastructure", "amrut", "rejuvenation"],
            "search_tags": ["urban development", "central", "infrastructure", "rejuvenation"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Swachh Bharat Mission - Urban (SBM-U)",
            "description": "SBM-U aims to make urban India free from open defecation and achieve 100% scientific management of municipal solid waste.",
            "short_description": "Clean India mission for urban areas",
            "sector": "urban_development",
            "ministry": "Ministry of Housing and Urban Affairs",
            "department": "Department of Housing and Urban Affairs",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "All urban areas",
            "benefits": "Improved sanitation and waste management",
            "application_process": "Implementation through urban local bodies",
            "application_link": None,
            "launch_date": "2014-10-02",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@sbm.gov.in",
            "website": "https://sbm.gov.in/",
            "source_url": "https://sbm.gov.in/",
            "keywords": ["sanitation", "urban development", "swachh bharat", "clean india"],
            "search_tags": ["urban development", "central", "sanitation", "clean india"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        },
        {
            "title": "Pradhan Mantri Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
            "description": "PM SVANidhi is a micro-credit facility for street vendors to resume their livelihoods that have been adversely affected due to COVID-19.",
            "short_description": "Micro-credit facility for street vendors",
            "sector": "urban_development",
            "ministry": "Ministry of Housing and Urban Affairs",
            "department": "Department of Housing and Urban Affairs",
            "government_level": "central",
            "state": None,
            "eligibility_criteria": "Street vendors in urban areas",
            "benefits": "Working capital loan up to Rs.10,000",
            "application_process": "Application through urban local bodies",
            "application_link": "https://pmsvanidhi.mohua.gov.in/",
            "launch_date": "2020-06-01",
            "last_date": None,
            "helpline_number": "1800-180-5522",
            "email": "support@pmsvanidhi.gov.in",
            "website": "https://pmsvanidhi.mohua.gov.in/",
            "source_url": "https://pmsvanidhi.mohua.gov.in/",
            "keywords": ["street vendors", "urban development", "micro-credit", "loan", "covid"],
            "search_tags": ["urban development", "central", "street vendors", "micro-credit"],
            "language": "en",
            "is_active": True,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        }
    ]
    
    return schemes_data

def setup_mongodb_with_sample_data():
    """Set up MongoDB with comprehensive sample data"""
    
    # Connect to MongoDB
    db = connect_mongodb()
    if db is None:
        return False
    
    # Create collections
    schemes_collection = db['government_schemes']
    
    # Clear existing data
    schemes_collection.delete_many({})
    print("Cleared existing schemes data")
    
    # Insert comprehensive sample data
    schemes_data = create_comprehensive_sample_data()
    
    try:
        result = schemes_collection.insert_many(schemes_data)
        print(f"[OK] Successfully inserted {len(result.inserted_ids)} schemes into MongoDB")
        
        # Create indexes for better performance
        schemes_collection.create_index("sector")
        schemes_collection.create_index("keywords")
        schemes_collection.create_index("search_tags")
        schemes_collection.create_index("is_active")
        schemes_collection.create_index([("title", "text"), ("description", "text"), ("keywords", "text")])
        print("[OK] Created indexes for better search performance")
        
        # Verify data
        total_schemes = schemes_collection.count_documents({})
        active_schemes = schemes_collection.count_documents({"is_active": True})
        
        print(f"\nDatabase Statistics:")
        print(f"Total schemes: {total_schemes}")
        print(f"Active schemes: {active_schemes}")
        
        # Show schemes by sector
        sectors = schemes_collection.distinct("sector")
        print(f"\nSectors covered: {len(sectors)}")
        for sector in sectors:
            count = schemes_collection.count_documents({"sector": sector, "is_active": True})
            print(f"  - {sector}: {count} schemes")
        
        return True
        
    except Exception as e:
        print(f"[ERROR] Error inserting data: {e}")
        return False

if __name__ == "__main__":
    print("Setting up MongoDB with comprehensive sample data...")
    success = setup_mongodb_with_sample_data()
    
    if success:
        print("\nMongoDB setup completed successfully!")
        print("Your chatbot now has comprehensive sample data for demo purposes.")
    else:
        print("\nMongoDB setup failed. Please check your MongoDB installation.")
