# Generated by Django 5.2 on 2025-10-14 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('pa', 'Punjabi')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='WebScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('source_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('schemes_found', models.IntegerField(default=0)),
                ('schemes_added', models.IntegerField(default=0)),
                ('schemes_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraping_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='admin', max_length=20)),
                ('can_scrape', models.BooleanField(default=True)),
                ('can_manage_schemes', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('text_content', models.TextField(help_text='Text content of the message')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chat_audio/')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('pa', 'Punjabi')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_schemes', models.JSONField(default=list, help_text='IDs of schemes mentioned in this response')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score for the response', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Scheme title', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of the scheme')),
                ('short_description', models.TextField(help_text='Brief description', max_length=1000)),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('health', 'Health'), ('education', 'Education'), ('employment', 'Employment'), ('social_welfare', 'Social Welfare'), ('rural_development', 'Rural Development'), ('urban_development', 'Urban Development'), ('women_empowerment', 'Women Empowerment'), ('youth_development', 'Youth Development'), ('senior_citizens', 'Senior Citizens'), ('disability', 'Disability'), ('other', 'Other')], help_text='Primary sector', max_length=50)),
                ('sub_sectors', models.JSONField(default=list, help_text='Additional sectors this scheme covers')),
                ('ministry', models.CharField(help_text='Responsible ministry', max_length=200)),
                ('department', models.CharField(help_text='Responsible department', max_length=200)),
                ('government_level', models.CharField(choices=[('central', 'Central'), ('state', 'State'), ('local', 'Local')], help_text='Level of government', max_length=20)),
                ('state', models.CharField(blank=True, help_text='State (if applicable)', max_length=100, null=True)),
                ('eligibility_criteria', models.TextField(help_text='Who can apply')),
                ('benefits', models.TextField(help_text='What benefits are provided')),
                ('financial_assistance', models.TextField(blank=True, help_text='Financial assistance details', null=True)),
                ('application_process', models.TextField(help_text='How to apply')),
                ('required_documents', models.JSONField(default=list, help_text='Documents required for application')),
                ('application_link', models.URLField(blank=True, help_text='Online application link', null=True)),
                ('launch_date', models.DateField(help_text='When the scheme was launched')),
                ('last_date', models.DateField(blank=True, help_text='Last date to apply', null=True)),
                ('validity_period', models.CharField(blank=True, help_text='Scheme validity period', max_length=100, null=True)),
                ('helpline_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('pa', 'Punjabi')], default='en', max_length=10)),
                ('title_translations', models.JSONField(default=dict, help_text='Translations of title in different languages')),
                ('description_translations', models.JSONField(default=dict, help_text='Translations of description')),
                ('source_url', models.URLField(help_text='Source URL where this information was scraped from')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the scheme is currently active')),
                ('keywords', models.JSONField(default=list, help_text='Keywords for search functionality')),
                ('search_tags', models.JSONField(default=list, help_text='Tags for better search and categorization')),
            ],
            options={
                'db_table': 'schemes',
                'indexes': [models.Index(fields=['sector'], name='schemes_sector_7428f1_idx'), models.Index(fields=['government_level'], name='schemes_governm_f9420f_idx'), models.Index(fields=['state'], name='schemes_state_a91b26_idx'), models.Index(fields=['language'], name='schemes_languag_ce9c18_idx'), models.Index(fields=['is_active'], name='schemes_is_acti_8232d5_idx')],
            },
        ),
    ]
